### PR TITLE
feat: introduce StreamValues for insert query

### PR DESCRIPTION
**Pull request by ygf11**
1. Introduce position map when tokenizer.
2. Support `StreamValues` for insert query.
3. Add some tests.

### CODE REVIEW

**Comment by ygf11** [comment]
@sundy-li Please take a look:)

**Comment by ygf11** [comment]
Since we use std `hashmap` in `tokenizer` now, the no-std build will not pass, should we use a non-std `hashmap` here?

**Comment by sundy-li** [comment]
> should we use a non-std hashmap here?

Better to use if we don't want to change the ci.

But if there is not a mature non-std hashmap crate, we can disable this ci.

**Comment by ygf11** [comment]
> Better to use if we don't want to change the ci.

Ok, replace std HashMap with `hashbrown` HashMap now.

**Review by sundy-li — APPROVED** [review]
LGTM, Great work

**Pull request merged**
